name: "PR-Builder"
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
      - name: Determine versioning
        id: version
        uses: paulhatch/semantic-version@v4.0.1
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: false
      - name: "Update plugin.json version to: ${{steps.version.outputs.prop}}"
        uses: jossef/action-set-json-field@v1
        with:
          file: 'plugin.json'
          field: Version
          value: "${{steps.version.outputs.major}}.${{steps.version.outputs.minor}}.${{steps.version.outputs.patch}}-dev"
      - name: Package files
        run: |
          git clone https://github.com/Garulf/flow_commands/ bin
          pip install -r ./bin/requirements.txt
          python ./bin/commands.py package -n "${{github.event.repository.name}}.zip"
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: "./${{github.event.repository.name}}.zip"
